create table users
(
	 id integer generated by default as identity primary key,
	 email varchar(255) not null,
	 name varchar(255) not null,
	 password varchar(255) not null,
	 created_at timestamp default now(),
	 updated_at timestamp default now()
);

create index users_email on users (email);